[pve]
pve-node-1 ansible_host=10.10.10.11 storage_ip=10.10.20.11
pve-node-2 ansible_host=10.10.10.12 storage_ip=10.10.20.12
pve-node-3 ansible_host=10.10.10.13 storage_ip=10.10.20.13

[pve_primary]
pve-node-1

[pve:vars]
ansible_user=root
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
cluster_name=poc-bencopharma
domain=poc.bencopharma.lab
ceph_network=10.10.20.0/24
