[prod]
dns01    ansible_host=10.10.30.10
krb01    ansible_host=10.10.30.12
docker01 ansible_host=10.10.30.13

[prod:vars]
ansible_user=benco
ansible_become=true
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
domain=poc.bencopharma.lab

[windows]
dc01 ansible_host=10.10.30.11

[windows:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
