[prod]
dns01    ansible_host=10.10.30.10
krb01    ansible_host=10.10.30.12
docker01 ansible_host=10.10.30.13

[prod:vars]
ansible_user=benco
ansible_become=true
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
domain=poc.bencopharma.lab

